### PR TITLE
feat(ai-help): add parent short_title for duplicate source titles

### PR DESCRIPTION
**Pull request by caugner**
Distinguish sources with the same title by appending the parent page's short title.

(MP-671)

### CODE REVIEW

**Comment by fiji-flo** [comment]
See https://github.com/mdn/rumba/pull/431

In general my first thought was to solve this in the front-end and just pull the `metadata.json` for the results.

Did we think about just displaying the URL with in the link for duplicates? That would also make the a lot easier. And in this solution we could do two queries instead of a single complex one (as in only get the parent titles if we need them).

**Comment by caugner** [comment]
@fiji-flo 

> In general my first thought was to solve this in the front-end and just pull the `metadata.json` for the results.

Hm, interesting idea that I hadn't considered. I don't think this is significantly better. The pure front-end implementation is likely more complex than solving this in the backend, and it introduces a dependency on loading the `metadata.json` files, which either adds some delay (and the potential of an error) or adds the suffixes only after some delay.

> Did we think about just displaying the URL with in the link for duplicates? That would also make the a lot easier. And in this solution we could do two queries instead of a single complex one (as in only get the parent titles if we need them).

I'm not quite sure what you mean. From a UX point of view, it's better to show the parent's title than the parent's slug, if that's what you mean. The SQL query isn't that complex and should be fast, since the `mdn_url` field has a unique index.

**Comment by caugner** [comment]
FYI @fiji-flo I cannot re-request a review, since your comment isn't a review comment.

**Review by argl — APPROVED** [review]
nice!

**Pull request merged**
