### PR TITLE
add sentry support

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Review by caugner — COMMENTED** [review]
- Maybe worth adding an example setting to `.settings.local.toml`?
- We don't see the stacktrace in https://sentry.io/organizations/mozilla/issues/3514936053/?project=6668368, and [the docs](https://docs.sentry.io/platforms/rust/guides/actix-web/) mention calling `std::env::set_var("RUST_BACKTRACE", "1");`

**Comment by caugner** [comment]
Hm, is it normal that we don't see the stacktrace in https://sentry.io/organizations/mozilla/issues/3514936053/?project=6668368?

**Review by Guyzeroth — APPROVED** [review]
This seems a bit magical but LGTM

**Comment by fiji-flo** [comment]
> * Maybe worth adding an example setting to `.settings.local.toml`?

I'm not sure if we wanna run this locally?

> * We don't see the stacktrace in https://sentry.io/organizations/mozilla/issues/3514936053/?project=6668368, and [the docs](https://docs.sentry.io/platforms/rust/guides/actix-web/) mention calling `std::env::set_var("RUST_BACKTRACE", "1");`

We have good errors, I don't think we need stack traces.

**Pull request merged**
